server:
  port: 8080

spring:
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://127.0.0.1:5432/db_bc2408"
    username: "postgres"
    password: "admin1234"
  jpa:
    show-sql: true
    hibernate.ddl-auto: create

api:
  jph:
    domain: "jsonplaceholder.typicode.com"
    endpoints:
      users: "/users" 
      posts: "/posts" 
      comments: "/comments" 